# Generated by Django 3.2.9 on 2022-01-01 15:19

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_user_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='national_card',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.national_card_image),
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
