# Generated by Django 3.2.9 on 2022-01-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social',
        ),
        migrations.AddField(
            model_name='user',
            name='existential',
            field=models.BooleanField(default=True),
        ),
    ]
