# Generated by Django 3.2.9 on 2022-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20220117_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='existential',
            field=models.BooleanField(default=False),
        ),
    ]
