# Generated by Django 3.2.9 on 2022-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_user_existential'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete_pro',
            field=models.BooleanField(default=False),
        ),
    ]
