# Generated by Django 3.2.9 on 2021-12-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfield',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
