# Generated by Django 3.2.9 on 2021-12-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
        ('projects', '0002_alter_jobfield_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status_jobField_user',
            field=models.IntegerField(choices=[(0, 'before confirm'), (1, 'progress'), (2, 'done')], default=1),
        ),
        migrations.AlterField(
            model_name='userjobfield',
            name='experience',
            field=models.DateField(),
        ),
    ]
