# Generated by Django 3.2.9 on 2021-12-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211218_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobfield',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
