# Generated by Django 3.2.9 on 2021-12-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_userjobfield_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jobField',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.jobfield'),
            preserve_default=False,
        ),
    ]
