# Generated by Django 3.2.9 on 2021-12-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_jobfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='jobField',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.jobfield'),
        ),
    ]
