# Generated by Django 3.2.9 on 2022-01-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status_jobField_user',
            field=models.IntegerField(choices=[(0, 'before confirm'), (1, 'progress'), (2, 'done')], default=0),
        ),
    ]
