# Generated by Django 3.2.9 on 2022-02-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20220117_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('jobfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.jobfield')),
            ],
        ),
    ]
