# Generated by Django 3.2.9 on 2022-02-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='jobfield',
        ),
        migrations.AddField(
            model_name='tag',
            name='jobfield',
            field=models.ManyToManyField(to='projects.JobField'),
        ),
    ]
