# Generated by Django 3.2.9 on 2022-02-21 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20220207_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjobfield',
            old_name='experience',
            new_name='expiration',
        ),
        migrations.RemoveField(
            model_name='userjobfield',
            name='state',
        ),
        migrations.AddField(
            model_name='userjobfield',
            name='inquiry_link',
            field=models.CharField(default=datetime.datetime(2022, 2, 21, 8, 10, 3, 278014, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userjobfield',
            name='issue',
            field=models.DateField(default=datetime.datetime(2022, 2, 21, 8, 10, 8, 314271, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userjobfield',
            name='national_card',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.document_image),
        ),
    ]
