# Generated by Django 3.2.9 on 2022-02-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20220221_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjobfield',
            old_name='national_card',
            new_name='document_image',
        ),
    ]
