# Generated by Django 3.2.9 on 2022-02-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
        ('projects', '0017_userstate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstate',
            unique_together={('state', 'jobField')},
        ),
    ]
