# Generated by Django 3.2.9 on 2022-02-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_userstate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
