# Generated by Django 3.2.9 on 2022-03-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_userstate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='userjobfield',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.userjobfield'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userstate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='jobField',
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='owner',
        ),
    ]
