# Generated by Django 3.2.9 on 2022-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='date',
            field=models.CharField(max_length=25),
        ),
    ]
