# Generated by Django 3.2.9 on 2022-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_alter_rule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='article',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rule',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
